In [1]:
import torch

### Inputs

In [2]:
x = torch.tensor([2, 3, 4.])
y = torch.tensor([4, 6, 8.])

### Weights

In [3]:
w = torch.tensor([1., 1., 1.], requires_grad=True)

### Forward Pass
> Making some predictions, by just multiplying the weights and the input `x` we are not going to add `bias` in this case.


```
              w   (multipy)
    input(x)---->(Network)----->output(y)
              f(x) = w + x + b
              
     f(x) = Network
        w = weights
        b = bias # in our case =0       
```

In [5]:
pred = w * x
pred

tensor([2., 3., 4.], grad_fn=<MulBackward0>)

### Calculating Losss
* The loss function thatwe are going to use is the `Mean Square Error Loss`

```
loss = math.pow((y_pred- y), 2)
```

In [9]:
loss = (pred -y)** 2
loss

tensor([ 4.,  9., 16.], grad_fn=<PowBackward0>)

### Basckward pass

In [12]:
v = torch.tensor([.1, .1, .1], dtype=torch.float32)
loss.backward(v)

### Updating the Weights
* update weights, this operation should not be part of the computational graph so we wrap it in the `with torch.no_grad()` statement.


In [15]:

for i in range(2):
    with torch.no_grad():
        w -=0.1 * w.grad
        # don't forget to zero the gradients
        w.grad.zero_()
        print(w)

tensor([1.0800, 1.1800, 1.3200], requires_grad=True)
tensor([1.0800, 1.1800, 1.3200], requires_grad=True)


> ` w.grad.zero_()` makes the gradient reamin the same.