# Pytorch
* Introduction to machine learning library based on the Torch library, used for applications such as computer vision and natural language processing, primarily developed by Facebook's AI Research lab

## Installation

In [4]:
!pip install torch==1.8.1+cpu torchvision==0.9.1+cpu torchaudio===0.8.1 -f https://download.pytorch.org/whl/torch_stable.html


Looking in links: https://download.pytorch.org/whl/torch_stable.html


## 1. Touch
* The torch package contains data structures for multi-dimensional tensors and defines mathematical operations over these tensors. 
* Additionally, it provides many utilities for efficient serializing of Tensors and arbitrary types, and other useful utilities.

In [6]:
import torch
import numpy as np
from matplotlib import pyplot as plt

In [14]:
# Creating tensors

t = torch.tensor([4., 1, 4])
t

tensor([4., 1., 4.])

### touch methods

#### 1.  TORCH.IS_TENSOR
* checks if an object is a tensor or not

In [21]:
print(torch.is_tensor([9, 8, -7, 8]))
torch.is_tensor(t)

False


True

#### 2. TORCH.IS_STORAGE
* returns true if the pytorch tensor is an object else false

In [22]:
torch.is_storage(t)

False

#### 3. TORCH.IS_COMPLEX
* Returns True if the data type of input is a complex data type i.e., one of torch.complex64, and torch.complex128.

In [25]:
c = torch.tensor([2, 5, 8, 9], dtype=torch.complex64)
print(torch.is_complex(c))
torch.is_complex(t)

True


False

#### 4.TORCH.IS_FLOATING_POINT
* Returns True if the data type of input is a floating point data type i.e., one of torch.float64, torch.float32, torch.float16, and torch.bfloat16.

In [27]:
print(torch.is_floating_point(torch.tensor([0, 6, 9])))
torch.is_floating_point(t)

False


True

#### 5. TORCH.IS_NONZERO
* Returns True if the input is a single element tensor which is not equal to zero after type conversions.

In [46]:
print(torch.is_nonzero(torch.tensor([9])))

True


#### 6. TORCH.SET_DEFAULT_DTYPE
* Sets the default floating point dtype to d

In [63]:
b = torch.tensor([9., 6, 8], dtype=torch.float32)
print(b.dtype)
torch.set_default_dtype(torch.float64)
torch.tensor([2, 5, .9]).dtype


torch.float32


torch.float64

#### 7. TORCH.NUMEL
* Returns the total number of elements in the input tensor.

In [69]:
b = torch.ones(8)
a = torch.zeros_like(b)
print(a)
print(torch.numel(a))

tensor([0., 0., 0., 0., 0., 0., 0., 0.])
8


#### 8. TORCH.SET_PRINTOPTIONS
* [Here](https://pytorch.org/docs/stable/generated/torch.set_printoptions.html#torch.set_printoptions)

#### 9. TORCH.SET_FLUSH_DENORMAL
* [Here](https://pytorch.org/docs/stable/generated/torch.set_flush_denormal.html#torch.set_flush_denormal)

In [73]:
torch.set_flush_denormal(False)

True

## Creation Ops
* [Here](https://pytorch.org/docs/stable/torch.html#creation-ops)

In [76]:
## torch.rand(n) 
ten = torch.rand(9)
ten

tensor([0.7801, 0.5808, 0.9566, 0.8771, 0.4297, 0.6235, 0.6755, 0.0372, 0.3678])

In [93]:
## torch.rand_like()
a = torch.tensor([4., 7, 8, 9])
ten = torch.randn_like(a)
ten

tensor([-1.7272,  1.0899, -0.0452, -1.0541])

In [98]:
## torch.randn()
ten = torch.randn([2, 5])
ten

tensor([[ 0.2572,  0.9909,  0.1526, -0.0797,  1.5206],
        [-0.6843, -1.2109,  1.2663,  1.1530, -0.0511]])

In [99]:
## torch.randn_like
ten = torch.randn_like(ten)
ten

tensor([[-0.5828, -0.5335,  0.8463,  0.3833,  1.8376],
        [ 1.0752, -0.2285, -1.9837, -0.2995, -0.1300]])

In [105]:
## touch.randint(low, high, size)
ten = torch.randint(0, 10, [5, 5])
ten

tensor([[1, 8, 8, 9, 4],
        [9, 9, 4, 9, 5],
        [9, 8, 1, 5, 0],
        [3, 6, 4, 9, 7],
        [7, 0, 9, 1, 5]])

In [111]:
## torch.randint_like()
ten = torch.randint_like(ten, 0, 9)
ten

tensor([[7, 4, 4, 4, 5],
        [7, 6, 5, 6, 7],
        [0, 5, 2, 3, 6],
        [2, 2, 3, 1, 0],
        [6, 1, 1, 4, 8]])

In [113]:
## torch.randperm()
    # Returns a random permutation of integers from
ten = torch.randperm(8)
ten

tensor([1, 7, 2, 6, 4, 5, 3, 0])

In [115]:
ten = torch.empty(9)
ten

tensor([2.1342e+161, 7.0981e+194, 7.4861e-114, 6.9558e+252, 1.6779e+243,
        5.9083e+223, 2.2830e-109, 2.9124e+257, 4.7129e+257])

In [116]:
## torch.tensor()
ten = torch.tensor(np.array([2, 6]), dtype=torch.int64)
ten

tensor([2, 6])

In [125]:
## torch.sparse_coo_tensor
indices  = torch.tensor([[0, 1, 1], [1, 0, 2]])
values = torch.tensor([2, 7, 8])

ten = torch.sparse_coo_tensor(indices, values, (2,3))
ten

tensor(indices=tensor([[0, 1, 1],
                       [1, 0, 2]]),
       values=tensor([2, 7, 8]),
       size=(2, 3), nnz=3, layout=torch.sparse_coo)

In [158]:
## torch.as_tensor
data = np.random.randint(0, 100, [2,7])
ten = torch.as_tensor(data)
ten[0][1:4]

tensor([11, 75, 44], dtype=torch.int32)

In [160]:
## torch.from_numpy
data = np.zeros([4,4])
ten = torch.from_numpy(data)
ten

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [169]:
## torch.zeros()
ten = torch.zeros([2,2, 2,2])
ten

tensor([[[[0., 0.],
          [0., 0.]],

         [[0., 0.],
          [0., 0.]]],


        [[[0., 0.],
          [0., 0.]],

         [[0., 0.],
          [0., 0.]]]])

In [170]:
## torch.zeros_like()

clone = torch.tensor([[8, 9, 10],[11, 12, -19]])

ten = torch.zeros_like(clone)
ten


tensor([[0, 0, 0],
        [0, 0, 0]])

In [172]:
## torch.ones()
ones = torch.ones([2, 4])
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [173]:
## torch.ones_like()
ones_like = torch.ones_like(clone)
ones_like

tensor([[1, 1, 1],
        [1, 1, 1]])

In [175]:
## torch.full()
full = torch.full([3,4], -9)
full

tensor([[-9, -9, -9, -9],
        [-9, -9, -9, -9],
        [-9, -9, -9, -9]])

In [177]:
## torch.full_like()
full_like = torch.full_like(clone, 7)
full_like

tensor([[7, 7, 7],
        [7, 7, 7]])

In [180]:
## torch.arange()
arange = torch.arange(0, 20, 2)
arange

tensor([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [182]:
even = torch.as_tensor([i for i in range(20) if i % 2 == 0])
even

tensor([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [183]:
## torch.range()
ten = torch.range(2, 10, 1)
ten

<ipython-input-183-ede0633240f5>:2: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  ten = torch.range(2, 10, 1)


tensor([ 2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [188]:
## torch.linspace()

ten = torch.linspace(0, 10, 5)
ten

tensor([ 0.0000,  2.5000,  5.0000,  7.5000, 10.0000])

In [190]:
## torch.logspace()
ten = torch.logspace(0, 10, 5)
ten

tensor([1.0000e+00, 3.1623e+02, 1.0000e+05, 3.1623e+07, 1.0000e+10])

In [198]:
## torch.eye(n, rows, columns)
ten = torch.eye(2)
ten

tensor([[1., 0.],
        [0., 1.]])

In [200]:
## torch.empty()
torch.empty(9)

tensor([1.2461e-306, 4.4506e-308, 9.3460e-307, 2.2252e-306, 2.1362e-306,
        4.4506e-308, 1.3796e-306, 8.4560e-307, 5.7312e-322])

In [201]:
## torch.empty_like()
torch.empty_like(clone)

tensor([[0, 0, 0],
        [0, 0, 0]])

## Indexing, Slicing, Joining, Mutating Ops

In [211]:
## torch.cat((...tensors), dim)
a = torch.full([2, 3],7)
cat = torch.cat([a, a, a], 1)
cat

tensor([[7, 7, 7, 7, 7, 7, 7, 7, 7],
        [7, 7, 7, 7, 7, 7, 7, 7, 7]])

In [218]:
## torch.chunk()
chunks = torch.chunk(cat, 3, 1)
chunks

(tensor([[7, 7, 7],
         [7, 7, 7]]),
 tensor([[7, 7, 7],
         [7, 7, 7]]),
 tensor([[7, 7, 7],
         [7, 7, 7]]))

In [220]:
# torch.column_stack()

col_stack = torch.column_stack((a, a))
col_stack

tensor([[7, 7, 7, 7, 7, 7],
        [7, 7, 7, 7, 7, 7]])

In [222]:
## torch.row_stack()
row_stack = torch.row_stack((a, a, a))
row_stack

tensor([[7, 7, 7],
        [7, 7, 7],
        [7, 7, 7],
        [7, 7, 7],
        [7, 7, 7],
        [7, 7, 7]])

In [223]:
## torch.vstack()
v_stack = torch.vstack([a, a, a])
v_stack

tensor([[7, 7, 7],
        [7, 7, 7],
        [7, 7, 7],
        [7, 7, 7],
        [7, 7, 7],
        [7, 7, 7]])

In [225]:
## torch.hstack()
h_stack = torch.hstack((a, a, a))
h_stack

tensor([[7, 7, 7, 7, 7, 7, 7, 7, 7],
        [7, 7, 7, 7, 7, 7, 7, 7, 7]])

In [226]:
## torch.dstack()
a = torch.tensor([1, 2, 3])
b = torch.tensor([4, 5, 6])

torch.dstack((a, b))

tensor([[[1, 4],
         [2, 5],
         [3, 6]]])

In [227]:
## torch.nonzero()

torch.nonzero(a)

tensor([[0],
        [1],
        [2]])

In [229]:
## torch.reshape()
a = torch.tensor([i for i in range(10)])
torch.reshape(a, [5, -1])

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])

In [230]:
## torch.split()
torch.split(a, 3)

(tensor([0, 1, 2]), tensor([3, 4, 5]), tensor([6, 7, 8]), tensor([9]))

In [234]:
## torch.swapaxes()
a = torch.reshape(a, [2, -1])

torch.swapaxes(a, 0, 1)

tensor([[0, 5],
        [1, 6],
        [2, 7],
        [3, 8],
        [4, 9]])

In [236]:
## torch.swapdims()
print(a)
torch.swapdims(a, 0, 1)

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])


tensor([[0, 5],
        [1, 6],
        [2, 7],
        [3, 8],
        [4, 9]])

In [237]:
## torch.t()
torch.t(a)


tensor([[0, 5],
        [1, 6],
        [2, 7],
        [3, 8],
        [4, 9]])

In [240]:
## torch.take()
torch.take(a, torch.tensor([0, 6, 7]))

tensor([0, 6, 7])

In [252]:
## tensor.tile()
torch.randint(5, 10, (4, )).tile(3,4)

tensor([[5, 9, 6, 6, 5, 9, 6, 6, 5, 9, 6, 6, 5, 9, 6, 6],
        [5, 9, 6, 6, 5, 9, 6, 6, 5, 9, 6, 6, 5, 9, 6, 6],
        [5, 9, 6, 6, 5, 9, 6, 6, 5, 9, 6, 6, 5, 9, 6, 6]])

In [270]:
## torch.transpose()
torch.transpose(a,1,0 )


tensor([[0, 5],
        [1, 6],
        [2, 7],
        [3, 8],
        [4, 9]])

In [272]:
## torch.unbind()
torch.unbind(a)

(tensor([0, 1, 2, 3, 4]), tensor([5, 6, 7, 8, 9]))

In [277]:
## torch.where()
b = torch.ones_like(a)
torch.where(a>10,a, b)

tensor([[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]])

## Generators

In [279]:
g_cpu = torch.Generator()
g_cpu.device

device(type='cpu')

In [280]:
g_cpu.get_state()

tensor([  1, 209, 156,  ...,   0,   0,   0], dtype=torch.uint8)

In [282]:
g_cpu.initial_seed()

67280421310721

## Random Sampling

In [284]:
## torch.seed()
seed = torch.seed()
seed

15798930354000

In [286]:
## torch.manual_seed
manual_seed = torch.manual_seed(99)
manual_seed


15874045848800