### Activation functions

In [1]:
import torch
import torch.nn as nn
from torch.nn import functional as F

In [2]:
x = torch.tensor([-1.0, 1.0, 2.0, 3.0])

### 1. Softmax

In [28]:
output2 = torch.softmax(x, dim=0)
output3 = F.softmax(x, dim=0)

output2, output3

(tensor([0.0120, 0.0889, 0.2418, 0.6572]),
 tensor([0.0120, 0.0889, 0.2418, 0.6572]))

### 2. Sigmoid

In [25]:
output2 = torch.sigmoid(x)
output3 = F.sigmoid(x)

output2, output3

(tensor([0.2689, 0.7311, 0.8808, 0.9526]),
 tensor([0.2689, 0.7311, 0.8808, 0.9526]))

### 3. tanh

In [30]:
output2 = torch.tanh(x)
output3 = F.tanh(x)

output2, output3

(tensor([-0.7616,  0.7616,  0.9640,  0.9951]),
 tensor([-0.7616,  0.7616,  0.9640,  0.9951]))

### 4. relu

In [31]:
output2 = torch.relu(x)
output3 = F.relu(x)

output2, output3

(tensor([0., 1., 2., 3.]), tensor([0., 1., 2., 3.]))

### 5. leaky_relu

In [32]:
output3 = F.leaky_relu(x)
output2, output3

(tensor([0., 1., 2., 3.]), tensor([-0.0100,  1.0000,  2.0000,  3.0000]))

> ``nn.ReLU()`` creates an ``nn.Module`` which you can add e.g. to an  ``nn.Sequential`` model.
* torch.relu on the other side is just the functional API call to the relu function.

**Usage Examples:**

In [37]:
class Net(nn.Module):
    def __init__(self, input_size, hidden_size):
        super(NeuralNet, self).__init__()
        self.linear1 = nn.Linear(input_size, hidden_size)
        self.relu = nn.ReLU()
        self.linear2 = nn.Linear(hidden_size, 1)
        self.sigmoid = nn.Sigmoid()
    
    def forward(self, x):
        out = self.linear1(x)
        out = self.relu(out)
        out = self.linear2(out)
        out = self.sigmoid(out)
        return out

> **OR**

In [36]:
class Net(nn.Module):
    def __init__(self, input_size, hidden_size):
        super(NeuralNet, self).__init__()
        self.linear1 = nn.Linear(input_size, hidden_size)
        self.linear2 = nn.Linear(hidden_size, 1)
    
    def forward(self, x):
        out = torch.relu(self.linear1(x))
        out = torch.sigmoid(self.linear2(out))
        return out