## Model_Losses_And_Optimizer_Full

In [1]:
import torch
import torch.nn as nn

### Data

> We are going to create a `2d` tensor for inputs and labels, this is very important in `pytorch`

In [2]:
X = torch.tensor([[0], [1], [2], [3], [4], [5.]], dtype=torch.float32)
y = torch.tensor([[0], [2], [4],[ 6], [8], [10.]], dtype=torch.float32)
X, y, X.ndim

(tensor([[0.],
         [1.],
         [2.],
         [3.],
         [4.],
         [5.]]),
 tensor([[ 0.],
         [ 2.],
         [ 4.],
         [ 6.],
         [ 8.],
         [10.]]),
 2)

### Test Data

In [3]:
X_test = torch.tensor([6., 7, 8, 9],  dtype=torch.float32).view(4, 1)
y_test = torch.tensor([12., 14, 16, 18],  dtype=torch.float32).view(4, 1)
X_test, y_test

(tensor([[6.],
         [7.],
         [8.],
         [9.]]),
 tensor([[12.],
         [14.],
         [16.],
         [18.]]))

### Model Creation
> We are going to use the `nn.Linear()` to create our model, since this is a linear regression problem. **Note that if the problem is linear** we should use `MSELoss` as our loss function.

In [4]:
_, n_features = X.shape
_, n_features

(6, 1)

In [5]:
input_size = n_features
output_size = n_features

In [6]:
model = nn.Linear(input_size, output_size)

### Optimizer and Loss

In [7]:
loss = nn.MSELoss()
optimizer = torch.optim.SGD(model.parameters(), lr=.01)

### Training the Model

In [8]:
EPOCHS = 200

for epoch in range(EPOCHS):
    # forward pass
    y_pred = model(X)
    ## loss
    l = loss(y_pred, y)
    ## gradiend - backward pass
    l.backward()
    ## updates the weights
    optimizer.step()
    ## zero the grad
    optimizer.zero_grad()

    if epoch%10 == 0:
        [w, b] = model.parameters() ## unpack weights and bias
        
        print(f'Epochs: {epoch+1}/{EPOCHS}, loss: {l}, weights: {w[0][0]}')

Epochs: 1/200, loss: 19.267501831054688, weights: 0.7174955606460571
Epochs: 11/200, loss: 0.3912017345428467, weights: 1.6846545934677124
Epochs: 21/200, loss: 0.14186982810497284, weights: 1.8018593788146973
Epochs: 31/200, loss: 0.12348330765962601, weights: 1.8242454528808594
Epochs: 41/200, loss: 0.10964884608983994, weights: 1.8355774879455566
Epochs: 51/200, loss: 0.09739154577255249, weights: 1.8451746702194214
Epochs: 61/200, loss: 0.08650478720664978, weights: 1.8540996313095093
Epochs: 71/200, loss: 0.07683498412370682, weights: 1.862497329711914
Epochs: 81/200, loss: 0.06824610382318497, weights: 1.870410442352295
Epochs: 91/200, loss: 0.060617316514253616, weights: 1.8778680562973022
Epochs: 101/200, loss: 0.05384130775928497, weights: 1.8848965167999268
Epochs: 111/200, loss: 0.047822728753089905, weights: 1.891520380973816
Epochs: 121/200, loss: 0.042476996779441833, weights: 1.8977631330490112
Epochs: 131/200, loss: 0.03772871941328049, weights: 1.9036465883255005
Epoch

### Making Predictions

In [9]:
model(torch.tensor([2], dtype=torch.float32))

tensor([4.0991], grad_fn=<AddBackward0>)

### Evaluating the Model

In [12]:

total, correct = 0, 0
with torch.no_grad():
    for x, y in zip(X_test, y_test):
        pred = torch.round(model(x))
        if pred == y:
            correct +=1
        total += 1
    print(f"Accuracy: {correct/total:.2f}")

Accuracy: 1.00


In [ ]:
> **100%** Acurate aga